apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatroom-be
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chatroom-be
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: chatroom-be
    spec:
      containers:
        - name: chatroom-be
          image: gauravchaurasiya/chatroom-be:1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: chatroom-be
            - secretRef:
                name: chatroom-be
          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  name: chatroom-be
spec:
  type: LoadBalancer
  selector:
    app: chatroom-be
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: chatroom-be
data:
  PORT: "5000"
  CLIENT_ORIGIN: "http://34.170.181.188"
---
apiVersion: v1
kind: Secret
metadata:
  name: chatroom-be
  labels:
    app: chatroom-be
  annotations:
    kubernetes.io/service-account.name: "chatroom-be"
type: Opaque
data:
  MONGO_URI: "bW9uZ29kYitzcnY6Ly9jaGF0cm9vbS1hZG1pbjpDcDg3VkhlbTZnSm9VYktJQGNoYXRyb29tLWNsdXN0ZXIudXM0anMubW9uZ29kYi5uZXQvY2hhdHJvb20/cmV0cnlXcml0ZXM9dHJ1ZSZ3PW1ham9yaXR5JmFwcE5hbWU9Q2hhdHJvb20tQ2x1c3Rlcg=="
  AUTH_TOKEN_PUBLIC_KEY: "LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KPj4gTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUF0R3VxbmxqZmhzc1JINzUxOVkzUAo+PiBHN1VNQy80Q0tzVVI0M0JvSzlpOWkwL1YrYjkzdGRSaWZGTWNDUUR3L0I3UkdRL2kyVWUwTTh2aEp3MXduSExtCj4+IG9tckF1aG1zdExlZTJJMllNMEhCTXpVL2VPNm5GRk9lM3F2REFpVTdmQ2VBSmN0Tkx0bTUvcTdYdlczS3lQc2kKPj4geENjZFNvektuNVNPQ2crSGRDT1QvRVlXajJEVWF0WUdTa0YwTVVtSmxKcUtlRkJpcFlROXhBblJEbGhFTFQ3SAo+PiBnWVBPcEhUU2ZzdTJya1c4dmp0bXRXMTA5SmgyNzlOc3lPMzRRQS9kejhpS0pSRlBkME16c3JvSmU3M3VUNE5OCj4+IHRFL1p4NEhiT3VCTWYwU1IxMjZ3TDNhbWVJWXhRbStSMnZzU1FOTUVvM29DZ29hY3VtZUtBZzFLTXlwTjRNeHoKPj4gOFFJREFRQUIKPj4gLS0tLS1FTkQgUFVCTElDIEtFWS0tLS0t"
  AUTH_TOKEN_PRIVATE_KEY: "LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2Z0lCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktnd2dnU2tBZ0VBQW9JQkFRQzBhNnFlV04rR3l4RWYKdm5YMWpjOGJ0UXdML2dJcXhSSGpjR2dyMkwyTFQ5WDV2M2UxMUdKOFV4d0pBUEQ4SHRFWkQrTFpSN1F6eStFbgpEWENjY3VhaWFzQzZHYXkwdDU3WWpaZ3pRY0V6TlQ5NDdxY1VVNTdlcThNQ0pUdDhKNEFseTAwdTJibitydGU5CmJjckkreUxFSngxS2pNcWZsSTRLRDRkMEk1UDhSaGFQWU5ScTFnWktRWFF4U1ltVW1vcDRVR0tsaEQzRUNkRU8KV0VRdFBzZUJnODZrZE5KK3k3YXVSYnkrTzJhMWJYVDBtSGJ2MDJ6STdmaEFEOTNQeUlvbEVVOTNRek95dWdsNwp2ZTVQZzAyMFQ5bkhnZHM2NEV4L1JKSFhickF2ZHFaNGhqRkNiNUhhK3hKQTB3U2plZ0tDaHB5Nlo0b0NEVW96CktrM2d6SFB4QWdNQkFBRUNnZ0VBQmNNN21aK3FrZzVaMzJyd3J4Vm10RktaemlkQWovZW43TjBLQXI2RFBWZ2gKTkQ4c2xtcndjMXFmTmwxb2xSRHg2a3hDMldCTUxleFk1bXVzT1Y4RkpWSm1FZnVnYzh3Nm4xMlVheXl5UEUyNgoxNFM5NHUwUjBiaG9PK0VQRDVYZVpyYWg0amx6a3FJb2cyVW1tVGxHUU1Ba0ZCMi9tZzIvWkt4ZXpmT1Y5alNFCkM0ajhFV3N1aXdsMFJSM2dvdnpOVnp5dENIWisvc3hpQXZzdHB3Q3hxZWFuNGhRR2tOV256Mi9KUmFBSTRlR3oKRnA4TlhVUk1LY1hHV00rK3YrSG5CeDZxQ1ZIOU94R2ZCSmVqcUorVVVsWDV6Mm1qMmsxSzVtTjVLQzFIMGlMdQo4OEhzUXB4STliczd2WW03bmw1WHBKTnQxdW1pay9PVTIySSsxMWxQZ1FLQmdRRDBoOFRkOWZURWhDaFd2anhzCkw3bkdjQVhDNXBrY2ZkZy9jZGRzRCtZUE5UZ2grM2s3RFF3cEQzT1V2MnlnQ0t3UUVwTTMxUmtBRXlVM1RxaWgKSEFzU205VUdqSXB3NGR0TDZ5YXBSSk9SMEhIcndyQmpQZnFqdjRBandCRi9kTWY5VFNqcldEUEk1MXpPQzdpNwpDLzdhY09xdnJtOGJBUnV5a1doeFRscFZZUUtCZ1FDODRoYzU4anc0ZTZaTkM1RzNRdUw4OVE3aENTNG5nWVhpCnhjbENQejNxbE5jZTA3eXVxdDFvSC9TbU43TXFtamVoRTBvU1JoZjE0NTkycXNQVzl4dU9PRGhoL1daTG9TbFUKNGQ2Q0VWdktkRFFDZE1tN1FrQzNQL055c0l5NzRqNi9WOVc3L1U1MUZYaWFKazdUYUxUNHNEaDZRazNyeEhwLwpZL3Y4bWtFWWtRS0JnUURRZ1h4aWJ6a1k0RCt0UjJVcU1yL0w3dlZhclZwZEt3bGJmK3phWGV3amg1T25sbEJYCkE5Y2NvK3BBS2NHcjYva2JjMXRJdmxJaytDNUJyTGFwT2NwUFFjVXhZbUVodzlSRU5leXZaS1FZTDQ4VUl0eFkKb3g2MnhiR3p5akNoWjZpbjJrVkw5OWVnTlhleTBkZmcxbWVuUjZVMXpCMDgvNExvam9ocUpROXR3UUtCZ1FDZgpzTWJTUnVxREZvZFRQQ1RHTzlhTTV1TGRmMVYyTVJ0d3pxZUpTczZlTlpocWg3bE9NMGRkY1NiMklNRnBrMWpVCjVlb0o2Umo0MnFsSE9yaTRWZE1HT3FId3RyeDExSnVOR0NsMjdoWWM1SUhVVWNqOGVOY2VGd05NUTllNFFWK3IKaGljOStMc01Za3JFaVA2NzNocWk1dG5aQTVXOWJ5L2g1RFozS2pNL0FRS0JnQWlKelQ5RVFhNTdma0poNEREVgpVY0I3amtKcUszTThRYXhXODVEZGFlVXBJR3hLVFg4ZFNXYzVRM2xrbUhNZ01xWWJqK3VJZjU5R3pMUGZrSC9YCnN6aXd0MWFFYU94MG1US1JvSmI5Mk9tUVRFekljYmlNMml0L0IyWWpQam1NazJub3Bpd21hV3B6Qnl1UFQ2ZDEKK0JtZ3BkU0ZCUlRKL3h4K1BYeTlYOHVMCi0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0="
  REFRESH_TOKEN_PUBLIC_KEY: "LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUFqOHNvQlFkR1Fjc3hkb2tSR1FRVwpaek4wSmVsZXgzbkl0RjRiZVo4K2Frc3RKMHVQRFJ1Nzh4bHZ3VHJURTVrRmpqSHJCcVBSa2tiSUVROG1YZGN4CkozMzlUSVBKSHVucGdzSTl6WjZkY0RYb1hzVytGTEVJVDRwMWFmVmtxZnJVWTZKM2ZZYk4zRFl6Wit6UCt0bHAKeGo5enBONlcyVklpUzUwOWxXdGh5UC95WXFZZmluZVI5K0MzZTB6NXZ5RXVnOXlWakIxcWFlZllJNm9jQVp1LwpuQWZDcGxNdGVhWG9TRlZUVWZ4VHFUR2QzL21hdG91SGl6dEZ1OFN5MFVFaXNWWm1yZ2NmaVVRR3JWeDJxR0pSCjUzWTdvMzcwTVdCOXFBSVZ3QWlhMW1wNFZZNzBhbFJvN1ZmVjdsNEd4QTgwTXA0SE0rUWR6SUl3YkZ6eU9qKzQKMXdJREFRQUIKLS0tLS1FTkQgUFVCTElDIEtFWS0tLS0t"
  REFRESH_TOKEN_PRIVATE_KEY: "LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2QUlCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktZd2dnU2lBZ0VBQW9JQkFRQ1B5eWdGQjBaQnl6RjIKaVJFWkJCWm5NM1FsNlY3SGVjaTBYaHQ1bno1cVN5MG5TNDhORzd2ekdXL0JPdE1UbVFXT01lc0dvOUdTUnNnUgpEeVpkMXpFbmZmMU1nOGtlNmVtQ3dqM05ucDF3TmVoZXhiNFVzUWhQaW5WcDlXU3ArdFJqb25kOWhzM2NOak5uCjdNLzYyV25HUDNPazNwYlpVaUpMblQyVmEySEkvL0ppcGgrS2Q1SDM0TGQ3VFBtL0lTNkQzSldNSFdwcDU5Z2oKcWh3Qm03K2NCOEttVXkxNXBlaElWVk5SL0ZPcE1aM2YrWnEyaTRlTE8wVzd4TExSUVNLeFZtYXVCeCtKUkFhdApYSGFvWWxIbmRqdWpmdlF4WUgyb0FoWEFDSnJXYW5oVmp2UnFWR2p0VjlYdVhnYkVEelF5bmdjejVCM01nakJzClhQSTZQN2pYQWdNQkFBRUNnZ0VBQTF0ZzBjMDdyS21MdkJLekhYeGs4WC9ZQkZLUWJlTy85Y1lFcWpBM2lzKzYKZkNKZGNwYmxLbVc3b0MwNVpFbThRWGVVM3hEUUFiUTVVM3loRHF2SmIveVcvMFJNVzdabVJ6RTF0Q2t4ejc3UwpiL1A1M2czTC9kOWpvbGVpUS8yaEc3cGRROGJ6NDJJNGpRS1FVSERtOFVQbDlVRmxFQ25FdHpNeWp0eDA2ZlpXCnd1Nk9mRmFYVXJUcEpnOXhPaUZ4MHFqd0g1SkZFbU40M05PQW9aWkhXUXJXdHRrVFg0Q0c5UzVrdGpYbnhHMUYKcHlPZHZpM2JOVVFPY0hRSjA1ZFM2SmcxTytDbWI0Z2JDTGxTa2l5ZlV1QTNYbCtMdjdGUytzaE92Q2g1ZmVVdgpTSjVJektCSFQzbjQ0R3hkYWNwYU1OUXNsZWdkYnBMUzB5b2NYaVNib1FLQmdRREFURjlhNXBjT0IyMGVWcGUxClhvOWZ6bW91dmlYWEpRbDNoVm5nRnN6a2QyTEtTYjNsNVpGdXpJQmJGU2gyZG8rdi9adXAzZ3hJVHNtYTBlOGQKMjY3eWFqbUhRNyswL1ExaGdwNlRKUSt6WVpWVktrcEJqZE03ZTlQQzV2d0pHMU54VWxpdHRqQ1QwOTlUM3l1SAp0cjFiYXIva3B5SDh2SXVXdWV6NW5EN0lEd0tCZ1FDL2JXV25Dc1FncXlSUUIzN1hCVzlZNWRlcXByK1ZLcXo1CjFYZlArdzJjcmREWlN1SGdFKzNwK01McXdEeng0OUZ2VWtKYVNxMHgvMVB2R0VUNGFOUmRJaDJTR1ZDNzFiNXEKSWFXVDgrV2NRN0pZSnhEZThGYnZLZlV1UzBzMG80MUsraisrV2thbFNYSEJreXdxWEtzeTc2RCtaU2ROSHFVTQpleEN0UjlaNnVRS0JnQTRVQ1U4Z1hxSzZUSFRTSmgwekpSQUFqcW1KWmovUUNGZGx2ZVM0QnB3YldYSXgzK002CjRXRFpPL1J2SWgwNkpON2ZsRXZsWThUUGI5Y1QwNHUrRDVyVHlBNXRHVlhveU5nQXRoZFR1VWlLdG1JYnpIL3MKSUREVXFmWTA3dkxEdTJJcWd5K0VqUjNsZnc0bTRvcjNCL252WU1rZXExQlRoV3l0Zy9ucVJIWmxBb0dBV1lkVgpvcEZqZHcvejFNWWNxWDN1UExxS2FsTEFpWWhERERtdFpvVTVNWTBOZjRNSkx4N0RCOG1EaC8xT3c2YlVIZWR3CkJ3Q2tEaDBuYVV5RmZWU3g5Ymp0OFpXTGI3NGc1MHhEUDNZemJpa3ZNUkZjVDVoQ1lHclVNOG1kSzhwT1c4RzgKckU5V2VSbG5iYXhpWEpHb3RCTGt6ZllMTW9OaGwvdTZxZ0JPTEdrQ2dZQUpkY0R6UzJPU0R1TlA4dXozUnJhbAorUzhRV0sySHdqQXRlNzE3THNMcDdtYVk2R29wbmhKYkxzTlhLcXVKZWV6TlFDQVVwRUFyM2twSDBMT2FNclNzClBuUmoxc05qVVFLUCtXK1VxWHRlbTR5dWtENlVmTTN0OEgwb2dIV1Frak1Gem1jK25sN014VGRrT0EzYy80bzMKRWF4VGJmUWNjN0pFRTBuUXNkb3RSZz09Ci0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0="
# [Convert]::ToBase64String([Text.Encoding]::UTF8.GetBytes(""))